#!/bin/sh /etc/rc.common

START=99
STOP=01

PROG="/usr/bin/router-bot.py" 
PYTHON_INTERPRETER="/usr/bin/python3"

USE_PROCD=1 
PROG_NAME="routerbot"

start_service() {
    procd_open_instance "${PROG_NAME}"
    
    procd_set_param command ${PYTHON_INTERPRETER} ${PROG}
    
    procd_set_param respawn 5 0 0 
    
    procd_close_instance
}

stop_service() {
    return 0
}

reload_service() {
    stop
    start
    logger -t "${PROG_NAME}" "Layanan di-restart paksa untuk memuat konfigurasi baru."
}